### ISSUE TITLE
fatal error: 'iostream' file not       found

### ISSUE THREAD

**Issue by ZZcat** [lopespm/agent-trainer#2]
Zachs-Mac:build zach$ make
Scanning dependencies of target cannonball
[  1%] Building CXX object CMakeFiles/cannonball.dir/Users/zach/Downloads/cannonball-master/src/main/romloader.cpp.o
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
/Users/zach/Downloads/cannonball-master/src/main/romloader.cpp:11:10: fatal error: 'iostream' file not
      found
#include <iostream>
         ^
1 error generated.
make[2]: *** [CMakeFiles/cannonball.dir/Users/zach/Downloads/cannonball-master/src/main/romloader.cpp.o] Error 1
make[1]: *** [CMakeFiles/cannonball.dir/all] Error 2
make: *** [all] Error 2

**Comment by lopespm** [comment]
@ZZcat, it seems cannonball build is failing because target SDK (MacOSX10.11.sdk) cannot be found on your machine, hence not finding the standard library iostream as well. If you install the SDK or point to one that is similiar, it should suffice to fix it. I think we can close this issue
